<p style="font-family:Calibri; font-size:1.75em; color:white; padding:5px 5px; text-align: left; height:50px; border-bottom: 1px solid orange;"></p>

<p style="font-size:2.5em; font-weight: 100; color:white; padding:25px; text-align:center; B"> 
1 - Upload Raw Sales Data into Desired Formate </p>
Upload Raw Sales Data into Desired Formate  <br>
f1a_salesUpload.py (f_cashflow views)

<p style="font-family:Calibri ; font-size:2em; font-weight: 800; color:white; padding:10px; text-align:center;
background: repeating-linear-gradient(135deg, rgba(68,68,68,0.07) 0px, rgba(68,68,68,0.07) 2px,transparent 2px, transparent 4px),repeating-linear-gradient(45deg, rgba(68,68,68,0.07) 0px, rgba(68,68,68,0.07) 2px,transparent 2px, transparent 4px),linear-gradient(135deg, rgb(251, 168, 16),rgb(251, 222, 55));">
 </p>

<p style="font-family:Calibri; font-size:1.75em; color:white; padding:5px 5px;
border-bottom: 3px solid orange; background: repeating-linear-gradient(135deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),repeating-linear-gradient(45deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),linear-gradient(90deg, rgb(77, 18, 84),rgb(52, 161, 185));"> 
 Step 1 -  Loading of Excel Data in Pandas </p>

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:5px; border-bottom: 3px solid dardkblue;
 background-color:#a0e6eb">
 Django Import - Import Pandas and Numpy Library</p>

In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:,.2f}'.format
pd.set_option('display.max_columns', 85) # set Jupeter note book to dispay 85 columns

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
1a. Define Option to Proceed Upload Process </p>

In [2]:
#selRegion = request.POST.get('num4', 'GCC')
selRegion = "GCC"
selAdmin = "Admin" #"Staff"

#to run different Region in Same Code....
if (selRegion == "GCC"):
    fileType = "GCC Data.xlsx"
if (selRegion == "Levant"):
    fileType = "LEB Data.xlsx"
if (selRegion == "MCS"):
    fileType = "MCS Data.xlsx"
if (selRegion == "MCS-2"):
    fileType = "MCS Data.xlsx"

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
1b. Read CSV files </p> 
<span style= "font-size:12px; color:darkblue;"> cData(Current Year Data) </span>

In [3]:
if( selRegion == "GCC"):
    Data = pd.read_excel("media/database/GCC Data.xlsx")
if( selRegion == "Levant"):
    Data = pd.read_excel("media/database/LEB Data.xlsx")
if( selRegion == "MCS"):
    Data = pd.read_excel("media/database/MCS Data.xlsx")
if( selRegion == "MCS-2"):
    Data = pd.read_excel("media/database/MCS Data-2.xlsx")
    
CounMaping = pd.read_excel("media/database/CounMaping.xlsx")
DeptMaping = pd.read_excel("media/database/DeptMaping.xlsx")

In [4]:
Data

,Document Type,DocEntry,Document No,Customer Code,Customer Name,Customer Group,Bill To Country,Bill to City,Brand,Business Unit,Company,Cost Center,Description,ItemCode,Item Type,Posting Date,Quantity,Qty FOC,FOC%,Qty Invoiced,Price,COGS,GM,GM%,Account Name,Total After Discount,Sales Employee,Supplier Name,Type
0,I,74957,231310455,41112535,11 11 Aesthetic & Dermatology Clinic LLC,Local Customers,United Arab Emirates,NaN,SRS,Skincare,MEDICA_TRADING_LLC_2018,Skincare,SRS HA3.5 5ml Box OF 5 (Hyaluronic Acid),I0002209,Product,2023-02-08,2,0.00,0.00,2.00,655.00,179.04,"1,130.96",0.86,Credit Sales,"1,310.00",Maya Samra,SRS International sprl Supplier,SALES INVOICE
1,I,75327,231310666,41111998,Acacia Medical Center,Local Customers,United Arab Emirates,Abu Dhabi,Kulzer,Dental,MEDICA_TRADING_LLC_2018,Dental,Venus Bulk Fill Plt Refill,I0006412,Product,2023-02-23,4,0.00,0.00,4.00,175.00,473.16,226.84,0.32,Credit Sales,700.00,Marwa Ahmed,Kulzer Mitsui Chemical Group,SALES INVOICE
2,I,74407,231310142,41111950,Adam & Eve Cosmetic Medical Center LLC,Local Customers,United Arab Emirates,Abu Dhabi,Cooltech,Equip,MEDICA_TRADING_LLC_2018,Equip,Cooltech Gel Pads (216gm) (Pack of 10),I0005792,Consumables,2023-01-13,1,0.00,0.00,1.00,840.00,384.72,455.28,0.54,Credit Sales,840.00,Amgad Ahmed,High Technology Products SL-Cocoon,SALES INVOICE
3,I,74836,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,Local Customers,United Arab Emirates,Abu Dhabi,Kulzer,Dental,MEDICA_TRADING_LLC_2018,Dental,Charisma Diamond Syr Row Refill 1 X 4G A2,I0006346,Product,2023-02-02,10,0.00,0.00,10.00,120.00,741.60,458.40,0.38,Credit Sales,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,SALES INVOICE
4,I,74836,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,Local Customers,United Arab Emirates,Abu Dhabi,Kulzer,Dental,MEDICA_TRADING_LLC_2018,Dental,Charisma Diamond Syr Row Refill 1 X 4G A3,I0006345,Product,2023-02-02,12,2.00,0.17,10.00,120.00,889.92,310.08,0.26,Credit Sales,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,SALES INVOICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2362,I,75639,231310812,41112462,Zieda Aesthetics Clinic LLC,Local Customers,United Arab Emirates,Dubai,ULTHERA,Equip,MEDICA_TRADING_LLC_2018,Equip,Transducers DS7-3.0,I0001503,Consumables,2023-03-07,1,0.20,0.20,0.80,"9,960.00","6,372.51","3,587.49",0.36,Credit Sales,"9,960.00",Ahmad Eddine,Merz Pharmaceuticals GMBH,SALES INVOICE
2363,I,74289,231310062,41111663,Zulekha Hospital LLC,Local Customers,United Arab Emirates,Dubai,Pal,Equip,MEDICA_TRADING_LLC_2018,Equip,Pal Power Assisted Lipoplasty PAL-650,I0001300,Applicators,2023-01-10,1,0.15,0.15,0.85,"45,050.00","23,085.88","21,964.12",0.49,Credit Sales,"45,050.00",Technical Dept,MicroAire Surgical Instruments,SALES INVOICE
2364,I,74289,231310062,41111663,Zulekha Hospital LLC,Local Customers,United Arab Emirates,Dubai,Pal,Tech,MEDICA_TRADING_LLC_2018,Tech,Pal Instrument Cable PAL-5006,I0001522,Spare Parts,2023-01-10,1,0.15,0.15,0.85,"9,350.00","4,542.06","4,807.94",0.51,Credit Sales,"9,350.00",Technical Dept,MicroAire Surgical Instruments,SALES INVOICE
2365,I,74316,231310084,41110563,Zulekha Medicine And Medical Equipment Store LLC,Local Customers,United Arab Emirates,Sharjah,Pal,Equip,MEDICA_TRADING_LLC_2018,Equip,Pal Aspiration Tubing Set PAL-1200,I0003625,Consumables,2023-01-10,4,0.00,0.00,4.00,600.00,"1,118.00","1,282.00",0.53,Credit Sales,"2,400.00",Mona El Sharif,MicroAire Surgical Instruments,SALES INVOICE
2366,I,74421,231310150,41110563,Zulekha Medicine And Medical Equipment Store LLC,Local Customers,United Arab Emirates,Sharjah,Pal,Equip,MEDICA_TRADING_LLC_2018,Equip,Pal Aspiration Tubing Set PAL-1200,I0003625,Consumables,2023-01-13,6,0.00,0.00,6.00,600.00,"1,677.00","1,923.00",0.53,Credit Sales,"3,600.00",Mona El Sharif,MicroAire Surgical Instruments,SALES INVOICE

<p style="font-family:Calibri; font-size:1.75em; color:white; padding:5px 5px;
border-bottom: 3px solid orange; background: repeating-linear-gradient(135deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),repeating-linear-gradient(45deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),linear-gradient(90deg, rgb(77, 18, 84),rgb(52, 161, 185));"> 
 Step 2 -  Conversion Proces </p>

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
2a. Rename and Delete Selected Column </p>

In [5]:
if( selRegion == "GCC"):
    Data.rename(columns = {'Posting Date':'Posting_Date'}, inplace=True)
    dropColumn = ['Document Type','DocEntry','Customer Group','Company','Cost Center','ItemCode','Qty FOC','FOC%','Qty Invoiced','Price','GM','GM%','Account Name','Bill to City']
    Data.drop(dropColumn, axis=1, inplace=True)
if( selRegion == "MCS"):
    Data.rename(columns = {'Posting Date':'Posting_Date'}, inplace=True)
    dropColumn = ['Document Type','DocEntry','Customer Group','Company','Cost Center','ItemCode','Qty FOC','FOC%','Qty Invoiced','Price','GM','GM%','Account Name','Bill to City']
    Data.drop(dropColumn, axis=1, inplace=True)
if( selRegion == "MCS-2"):
    Data.rename(columns = {'Posting Date':'Posting_Date'}, inplace=True)
    dropColumn = ['Document Type','DocEntry','Customer Group','Company','Cost Center','ItemCode','Qty FOC','FOC%','Qty Invoiced','Price','GM','GM%','Account Name','Bill to City']
    Data.drop(dropColumn, axis=1, inplace=True)
if( selRegion == "Levant"):
    Data.rename(columns = {'Document No':'Document No','CardCode':'Customer Code','CardName':'Customer Name',
                            'Dscription':'Description','U_Type':'Item Type',
                            'DocDate':'Posting_Date','GM%':'Sum of COGS','Total After Discount':'Sum of Total After Discount',
                            'SlpName':'Sales Employee','U_Supplier_Name':'Supplier Name'}, inplace=True)
    
    dropColumn = ['DocType','DocEntry','GroupName','Bill to City Hierarchy - Bill To Country','U_BusinessUnit','ItemCode','Quantity','Qty FOC','FOC%','Qty Invoiced','AcctName','AcctName']
    Data.drop(dropColumn, axis=1, inplace=True)

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
2b. Add Columns </p>

In [6]:
Data['Item_Type'] = Data['Item Type']
Data['Type'] = 'In Market'
Data['Month'] = Data['Posting_Date'].dt.month_name()

In [7]:
if( selRegion == "Levant"):
    Data['Sum of COGS'] = Data['Sum of Total After Discount'] - Data['GM']
    Data.drop('GM', axis=1, inplace=True)

In [8]:
Data

,Document No,Customer Code,Customer Name,Bill To Country,Brand,Business Unit,Description,Item Type,Posting_Date,Quantity,COGS,Total After Discount,Sales Employee,Supplier Name,Type,Item_Type,Month
0,231310455,41112535,11 11 Aesthetic & Dermatology Clinic LLC,United Arab Emirates,SRS,Skincare,SRS HA3.5 5ml Box OF 5 (Hyaluronic Acid),Product,2023-02-08,2,179.04,"1,310.00",Maya Samra,SRS International sprl Supplier,In Market,Product,February
1,231310666,41111998,Acacia Medical Center,United Arab Emirates,Kulzer,Dental,Venus Bulk Fill Plt Refill,Product,2023-02-23,4,473.16,700.00,Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
2,231310142,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Cooltech,Equip,Cooltech Gel Pads (216gm) (Pack of 10),Consumables,2023-01-13,1,384.72,840.00,Amgad Ahmed,High Technology Products SL-Cocoon,In Market,Consumables,January
3,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Kulzer,Dental,Charisma Diamond Syr Row Refill 1 X 4G A2,Product,2023-02-02,10,741.60,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
4,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Kulzer,Dental,Charisma Diamond Syr Row Refill 1 X 4G A3,Product,2023-02-02,12,889.92,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2362,231310812,41112462,Zieda Aesthetics Clinic LLC,United Arab Emirates,ULTHERA,Equip,Transducers DS7-3.0,Consumables,2023-03-07,1,"6,372.51","9,960.00",Ahmad Eddine,Merz Pharmaceuticals GMBH,In Market,Consumables,March
2363,231310062,41111663,Zulekha Hospital LLC,United Arab Emirates,Pal,Equip,Pal Power Assisted Lipoplasty PAL-650,Applicators,2023-01-10,1,"23,085.88","45,050.00",Technical Dept,MicroAire Surgical Instruments,In Market,Applicators,January
2364,231310062,41111663,Zulekha Hospital LLC,United Arab Emirates,Pal,Tech,Pal Instrument Cable PAL-5006,Spare Parts,2023-01-10,1,"4,542.06","9,350.00",Technical Dept,MicroAire Surgical Instruments,In Market,Spare Parts,January
2365,231310084,41110563,Zulekha Medicine And Medical Equipment Store LLC,United Arab Emirates,Pal,Equip,Pal Aspiration Tubing Set PAL-1200,Consumables,2023-01-10,4,"1,118.00","2,400.00",Mona El Sharif,MicroAire Surgical Instruments,In Market,Consumables,January
2366,231310150,41110563,Zulekha Medicine And Medical Equipment Store LLC,United Arab Emirates,Pal,Equip,Pal Aspiration Tubing Set PAL-1200,Consumables,2023-01-13,6,"1,677.00","3,600.00",Mona El Sharif,MicroAire Surgical Instruments,In Market,Consumables,January

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
2ba. Filter Date for current month </p>

In [9]:
if( selAdmin == "Staff"):
    Data = Data.sort_values(by='Posting_Date')

    from datetime import date
    today = date.today()
    monthStart = str(today.year)+"-"+str(today.month)
    monthEnd = str(today.year)+"-"+str(today.month+1)

    Data = Data[(Data['Posting_Date'] >=monthStart) & (Data['Posting_Date'] <monthEnd)].reset_index()

In [10]:
from datetime import date
today = date.today()

In [11]:
abc = today.month
if (abc == 12):
    yr = today.year+1
    mt = 1
    
    monthStart = str(today.year)+"-"+str(today.month)
    monthEnd = str(yr)+"-"+str(mt)
    
else:
    monthStart = str(today.year)+"-"+str(today.month)
    monthEnd = str(today.year)+"-"+str(today.month+1)

In [12]:
#Data = Data[(Data['Posting_Date'] >=monthStart) & (Data['Posting_Date'] <monthEnd)].reset_index()

In [13]:
Data

,Document No,Customer Code,Customer Name,Bill To Country,Brand,Business Unit,Description,Item Type,Posting_Date,Quantity,COGS,Total After Discount,Sales Employee,Supplier Name,Type,Item_Type,Month
0,231310455,41112535,11 11 Aesthetic & Dermatology Clinic LLC,United Arab Emirates,SRS,Skincare,SRS HA3.5 5ml Box OF 5 (Hyaluronic Acid),Product,2023-02-08,2,179.04,"1,310.00",Maya Samra,SRS International sprl Supplier,In Market,Product,February
1,231310666,41111998,Acacia Medical Center,United Arab Emirates,Kulzer,Dental,Venus Bulk Fill Plt Refill,Product,2023-02-23,4,473.16,700.00,Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
2,231310142,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Cooltech,Equip,Cooltech Gel Pads (216gm) (Pack of 10),Consumables,2023-01-13,1,384.72,840.00,Amgad Ahmed,High Technology Products SL-Cocoon,In Market,Consumables,January
3,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Kulzer,Dental,Charisma Diamond Syr Row Refill 1 X 4G A2,Product,2023-02-02,10,741.60,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
4,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Kulzer,Dental,Charisma Diamond Syr Row Refill 1 X 4G A3,Product,2023-02-02,12,889.92,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2362,231310812,41112462,Zieda Aesthetics Clinic LLC,United Arab Emirates,ULTHERA,Equip,Transducers DS7-3.0,Consumables,2023-03-07,1,"6,372.51","9,960.00",Ahmad Eddine,Merz Pharmaceuticals GMBH,In Market,Consumables,March
2363,231310062,41111663,Zulekha Hospital LLC,United Arab Emirates,Pal,Equip,Pal Power Assisted Lipoplasty PAL-650,Applicators,2023-01-10,1,"23,085.88","45,050.00",Technical Dept,MicroAire Surgical Instruments,In Market,Applicators,January
2364,231310062,41111663,Zulekha Hospital LLC,United Arab Emirates,Pal,Tech,Pal Instrument Cable PAL-5006,Spare Parts,2023-01-10,1,"4,542.06","9,350.00",Technical Dept,MicroAire Surgical Instruments,In Market,Spare Parts,January
2365,231310084,41110563,Zulekha Medicine And Medical Equipment Store LLC,United Arab Emirates,Pal,Equip,Pal Aspiration Tubing Set PAL-1200,Consumables,2023-01-10,4,"1,118.00","2,400.00",Mona El Sharif,MicroAire Surgical Instruments,In Market,Consumables,January
2366,231310150,41110563,Zulekha Medicine And Medical Equipment Store LLC,United Arab Emirates,Pal,Equip,Pal Aspiration Tubing Set PAL-1200,Consumables,2023-01-13,6,"1,677.00","3,600.00",Mona El Sharif,MicroAire Surgical Instruments,In Market,Consumables,January

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
2c. Filter Data to exclue within Company sales  </p>

In [14]:
if( selRegion == "GCC"):
    InterCompany = ['M1111111','40110306','40110300','41112051','45110014','41700119']
    Data = Data[~Data['Customer Code'].isin(InterCompany)]

In [15]:
Data

,Document No,Customer Code,Customer Name,Bill To Country,Brand,Business Unit,Description,Item Type,Posting_Date,Quantity,COGS,Total After Discount,Sales Employee,Supplier Name,Type,Item_Type,Month
0,231310455,41112535,11 11 Aesthetic & Dermatology Clinic LLC,United Arab Emirates,SRS,Skincare,SRS HA3.5 5ml Box OF 5 (Hyaluronic Acid),Product,2023-02-08,2,179.04,"1,310.00",Maya Samra,SRS International sprl Supplier,In Market,Product,February
1,231310666,41111998,Acacia Medical Center,United Arab Emirates,Kulzer,Dental,Venus Bulk Fill Plt Refill,Product,2023-02-23,4,473.16,700.00,Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
2,231310142,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Cooltech,Equip,Cooltech Gel Pads (216gm) (Pack of 10),Consumables,2023-01-13,1,384.72,840.00,Amgad Ahmed,High Technology Products SL-Cocoon,In Market,Consumables,January
3,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Kulzer,Dental,Charisma Diamond Syr Row Refill 1 X 4G A2,Product,2023-02-02,10,741.60,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
4,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Kulzer,Dental,Charisma Diamond Syr Row Refill 1 X 4G A3,Product,2023-02-02,12,889.92,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2362,231310812,41112462,Zieda Aesthetics Clinic LLC,United Arab Emirates,ULTHERA,Equip,Transducers DS7-3.0,Consumables,2023-03-07,1,"6,372.51","9,960.00",Ahmad Eddine,Merz Pharmaceuticals GMBH,In Market,Consumables,March
2363,231310062,41111663,Zulekha Hospital LLC,United Arab Emirates,Pal,Equip,Pal Power Assisted Lipoplasty PAL-650,Applicators,2023-01-10,1,"23,085.88","45,050.00",Technical Dept,MicroAire Surgical Instruments,In Market,Applicators,January
2364,231310062,41111663,Zulekha Hospital LLC,United Arab Emirates,Pal,Tech,Pal Instrument Cable PAL-5006,Spare Parts,2023-01-10,1,"4,542.06","9,350.00",Technical Dept,MicroAire Surgical Instruments,In Market,Spare Parts,January
2365,231310084,41110563,Zulekha Medicine And Medical Equipment Store LLC,United Arab Emirates,Pal,Equip,Pal Aspiration Tubing Set PAL-1200,Consumables,2023-01-10,4,"1,118.00","2,400.00",Mona El Sharif,MicroAire Surgical Instruments,In Market,Consumables,January
2366,231310150,41110563,Zulekha Medicine And Medical Equipment Store LLC,United Arab Emirates,Pal,Equip,Pal Aspiration Tubing Set PAL-1200,Consumables,2023-01-13,6,"1,677.00","3,600.00",Mona El Sharif,MicroAire Surgical Instruments,In Market,Consumables,January

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
2d. Classify Intercompany Transaction as 'IC'  </p>

In [16]:
Data1 = Data.copy(deep=True)

In [17]:
if( selRegion == "GCC"):
    Data1.loc[Data1["Customer Code"] == 41110712, "Type"] = "IC"
    
if( selRegion == "Levant"):
    Data1.loc[Data1["Customer Code"] == 'C1177', ["Type"]] = "IC"

In [18]:
Data1

,Document No,Customer Code,Customer Name,Bill To Country,Brand,Business Unit,Description,Item Type,Posting_Date,Quantity,COGS,Total After Discount,Sales Employee,Supplier Name,Type,Item_Type,Month
0,231310455,41112535,11 11 Aesthetic & Dermatology Clinic LLC,United Arab Emirates,SRS,Skincare,SRS HA3.5 5ml Box OF 5 (Hyaluronic Acid),Product,2023-02-08,2,179.04,"1,310.00",Maya Samra,SRS International sprl Supplier,In Market,Product,February
1,231310666,41111998,Acacia Medical Center,United Arab Emirates,Kulzer,Dental,Venus Bulk Fill Plt Refill,Product,2023-02-23,4,473.16,700.00,Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
2,231310142,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Cooltech,Equip,Cooltech Gel Pads (216gm) (Pack of 10),Consumables,2023-01-13,1,384.72,840.00,Amgad Ahmed,High Technology Products SL-Cocoon,In Market,Consumables,January
3,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Kulzer,Dental,Charisma Diamond Syr Row Refill 1 X 4G A2,Product,2023-02-02,10,741.60,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
4,231310396,41111950,Adam & Eve Cosmetic Medical Center LLC,United Arab Emirates,Kulzer,Dental,Charisma Diamond Syr Row Refill 1 X 4G A3,Product,2023-02-02,12,889.92,"1,200.00",Marwa Ahmed,Kulzer Mitsui Chemical Group,In Market,Product,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2362,231310812,41112462,Zieda Aesthetics Clinic LLC,United Arab Emirates,ULTHERA,Equip,Transducers DS7-3.0,Consumables,2023-03-07,1,"6,372.51","9,960.00",Ahmad Eddine,Merz Pharmaceuticals GMBH,In Market,Consumables,March
2363,231310062,41111663,Zulekha Hospital LLC,United Arab Emirates,Pal,Equip,Pal Power Assisted Lipoplasty PAL-650,Applicators,2023-01-10,1,"23,085.88","45,050.00",Technical Dept,MicroAire Surgical Instruments,In Market,Applicators,January
2364,231310062,41111663,Zulekha Hospital LLC,United Arab Emirates,Pal,Tech,Pal Instrument Cable PAL-5006,Spare Parts,2023-01-10,1,"4,542.06","9,350.00",Technical Dept,MicroAire Surgical Instruments,In Market,Spare Parts,January
2365,231310084,41110563,Zulekha Medicine And Medical Equipment Store LLC,United Arab Emirates,Pal,Equip,Pal Aspiration Tubing Set PAL-1200,Consumables,2023-01-10,4,"1,118.00","2,400.00",Mona El Sharif,MicroAire Surgical Instruments,In Market,Consumables,January
2366,231310150,41110563,Zulekha Medicine And Medical Equipment Store LLC,United Arab Emirates,Pal,Equip,Pal Aspiration Tubing Set PAL-1200,Consumables,2023-01-13,6,"1,677.00","3,600.00",Mona El Sharif,MicroAire Surgical Instruments,In Market,Consumables,January

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
2e. Apply Merge data to map country and Vertical  </p> 
vlookup formula to map standard name...

In [19]:
Join = pd.merge(Data1, CounMaping, on ='Bill To Country', how ='left')
Join = pd.merge(Join, DeptMaping, on ='Business Unit', how ='left')

In [20]:
Join.drop(['Bill To Country','Business Unit'], axis=1, inplace=True)
Join.rename(columns = {'Vertical':'Business Unit','Country':'Bill To Country','COGS':'Sum of COGS','Total After Discount':'Sum of Total After Discount'}, inplace=True)

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
2f. Country and Vertical Column having blank to 'Others'  </p>

In [21]:
### ----------------------------------------------Option 1
#df1 = df.replace(np.nan, '', regex=True) # All data frame

### ----------------------------------------------Option 2
Join[['Bill To Country','Business Unit']] = Join[['Bill To Country','Business Unit']].fillna('i. Others') # Specific columns

if( selRegion == "Levant"):
    Join['Sum of COGS'] = Join['Sum of COGS'].div(410)
    Join['Sum of Total After Discount'] = Join['Sum of Total After Discount'].div(410)
if( selRegion == "MCS"):
    Join['Sum of COGS'] = Join['Sum of COGS'].mul(0.98)
    Join['Sum of Total After Discount'] = Join['Sum of Total After Discount'].mul(0.98)
if( selRegion == "MCS-2"):
    Join['Sum of COGS'] = Join['Sum of COGS'].mul(0.98)
    Join['Sum of Total After Discount'] = Join['Sum of Total After Discount'].mul(0.98)

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
2g. Rearrange Column  </p>

In [22]:
colNames = ["Document No", "Customer Code", "Customer Name", "Bill To Country", "Brand", "Business Unit", "Description", 
            "Item Type", "Posting_Date", "Month", "Sum of COGS", "Sum of Total After Discount", "Sales Employee", "Supplier Name",
           "Item_Type","Type"]
Join = Join.reindex(columns=colNames)

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
2h. Save data as CSV file  </p>

In [23]:
if( selRegion == "GCC"):
    Join.to_csv(r'media/database/TemporaryGCC.csv', index = False)
if( selRegion == "MCS"):
    Join.to_csv(r'media/database/TemporaryMCS.csv', index = False)
if( selRegion == "MCS-2"):
    Join.to_csv(r'media/database/TemporaryMCS-2.csv', index = False)
if( selRegion == "Levant"):
    Join.to_csv(r'media/database/TemporaryLEB.csv', index = False)

<p style="font-family:Calibri; font-size:1.75em; color:white; padding:5px 5px; text-align: left; height:75px;">
</p>

<p style="font-family:Calibri ; font-size:3em; font-weight: 100; color:white; padding:25px; text-align:center;
border-bottom: 5px solid orange; background: linear-gradient(41deg, rgba(107, 107, 107, 0.04) 0%, rgba(107, 107, 107, 0.04) 8%,rgba(31, 31, 31, 0.04) 8%, rgba(31, 31, 31, 0.04) 100%),linear-gradient(9deg, rgba(228, 228, 228, 0.04) 0%, rgba(228, 228, 228, 0.04) 62%,rgba(54, 54, 54, 0.04) 62%, rgba(54, 54, 54, 0.04) 100%),linear-gradient(124deg, rgba(18, 18, 18, 0.04) 0%, rgba(18, 18, 18, 0.04) 37%,rgba(233, 233, 233, 0.04) 37%, rgba(233, 233, 233, 0.04) 100%),linear-gradient(253deg, rgba(201, 201, 201, 0.04) 0%, rgba(201, 201, 201, 0.04) 55%,rgba(47, 47, 47, 0.04) 55%, rgba(47, 47, 47, 0.04) 100%),linear-gradient(270deg, rgba(172, 172, 172, 0.04) 0%, rgba(172, 172, 172, 0.04) 33%,rgba(26, 26, 26, 0.04) 33%, rgba(26, 26, 26, 0.04) 100%),linear-gradient(64deg, rgba(11, 11, 11, 0.04) 0%, rgba(11, 11, 11, 0.04) 38%,rgba(87, 87, 87, 0.04) 38%, rgba(87, 87, 87, 0.04) 100%),linear-gradient(347deg, rgba(199, 199, 199, 0.04) 0%, rgba(199, 199, 199, 0.04) 69%,rgba(4, 4, 4, 0.04) 69%, rgba(4, 4, 4, 0.04) 100%),linear-gradient(313deg, rgba(36, 36, 36, 0.04) 0%, rgba(36, 36, 36, 0.04) 20%,rgba(91, 91, 91, 0.04) 20%, rgba(91, 91, 91, 0.04) 100%),linear-gradient(90deg, rgb(10, 17, 72),rgb(35, 148, 228));"> 
Process 1 - Sales Summary from Actual Sales Data </p>
f1_Sal_Convrsion.py (Django views)

<p style=" margin:0px; padding:0px;">
    - Objective is to create Summary Data Sheet from Initial Actual Sales Report.  <br>
    - Budgeted Sales Summary is in Complete Budget Summary File where all the PnL Item is there.  <br>
    - Django Dashboard Views name ( f1_Sal_Convrsion.py )   <br>
      <br>
    Terminology Used in this file     <br>
    'CYear'  =   Current Year Sales 
</p>

<p style="font-family:Calibri ; font-size:2em; font-weight: 800; color:white; padding:10px; text-align:center;
background: repeating-linear-gradient(135deg, rgba(68,68,68,0.07) 0px, rgba(68,68,68,0.07) 2px,transparent 2px, transparent 4px),repeating-linear-gradient(45deg, rgba(68,68,68,0.07) 0px, rgba(68,68,68,0.07) 2px,transparent 2px, transparent 4px),linear-gradient(135deg, rgb(251, 168, 16),rgb(251, 222, 55));">
 </p>

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:5px; border-bottom: 3px solid dardkblue;
 background-color:#a0e6eb">
 Django Import - Import Pandas and Numpy Library</p>

In [24]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:,.2f}'.format
pd.set_option('display.max_columns', 85) # set Jupeter note book to dispay 85 columns

<p style="font-family:Calibri; font-size:1.75em; color:white; padding:5px 5px;
border-bottom: 3px solid orange; background: repeating-linear-gradient(135deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),repeating-linear-gradient(45deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),linear-gradient(90deg, rgb(77, 18, 84),rgb(52, 161, 185));"> 
 Step 1 -  Loading of Excel Data in Pandas Based on Region and Type</p>

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:5px; border-bottom: 3px solid dardkblue;
 background-color:#a0e6eb">
Define Values for Repor</p>

In [25]:
Option = "Yes"
cYear = "2023"
selRegion = "GCC"    ### from Top

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
1a. Select Columns to load Data</p>

In [26]:
req_cols = ['Bill To Country','Business Unit','Month','Sum of COGS','Sum of Total After Discount', 'Type']

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
1b. Read CSV files based on Selected Region and Year </p> 
<span style= "font-size:12px; color:darkblue;"> cData(Current Year Data) </span>

In [27]:
#selRegion = request.POST.get('num4', 'GCC')
#selRegion = "GCC"

if( selRegion == "GCC"):
    tData = pd.read_csv("media/database/TemporaryGCC.csv" ,usecols=req_cols)
    aData = pd.read_csv("DataBase/1_Sales/"+cYear+" "+selRegion+" "+"Sales.csv" ,usecols=req_cols)
    Act_frames = (tData , aData)
    cData = pd.concat(Act_frames)
elif( selRegion == "Levant"):
    tData = pd.read_csv("media/database/TemporaryLEB.csv" ,usecols=req_cols)
    aData = pd.read_csv("DataBase/1_Sales/"+cYear+" "+selRegion+" "+"Sales.csv" ,usecols=req_cols)
    Act_frames = (tData , aData)
    cData = pd.concat(Act_frames)
elif( selRegion == "MCS"):
    tData = pd.read_csv("media/database/TemporaryMCS.csv" ,usecols=req_cols)
    aData = pd.read_csv("DataBase/1_Sales/"+cYear+" "+selRegion+" "+"Sales.csv" ,usecols=req_cols)
    Act_frames = (tData , aData)
    cData = pd.concat(Act_frames)
elif( selRegion == "MCS-2"):
    tData = pd.read_csv("media/database/TemporaryMCS-2.csv" ,usecols=req_cols)
    aData = pd.read_csv("DataBase/1_Sales/"+cYear+" MCS Sales-2.csv" ,usecols=req_cols)
    Act_frames = (tData , aData)
    cData = pd.concat(Act_frames)
else:
    pass

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#fbfcb3">
1c. Rename the selected Column as per requirement</p>

In [28]:
cData.rename(columns = {'Bill To Country':'Country', 'Business Unit':'Vertical', 'Sum of COGS':'CY_CoS', 'Sum of Total After Discount':'CY_Revenue'}, inplace=True)

<p style="font-family:Calibri ; font-size:1.5em; color:darkblue; padding:3px; border-bottom: 3px solid dardkblue;
 background-color:#a0e6eb">
 Django - Check Performance and Memory Utilization</p>

In [29]:
#%timeit CYear
#pData.info(memory_usage='deep')

<p style="font-family:Calibri; font-size:1.75em; color:white; padding:5px 5px;
border-bottom: 3px solid orange; background: repeating-linear-gradient(135deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),repeating-linear-gradient(45deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),linear-gradient(90deg, rgb(77, 18, 84),rgb(52, 161, 185));"> 
STEP 2- Create Pivot Table - By Vertica, By Country , Month </p>
<span style= "font-size:12px;"> Create Pivot Table - By Vertica, By Country , Month </span>

In [30]:
df_pivot = pd.pivot_table(cData ,index=["Vertical","Country","Month","Type"],aggfunc=np.sum)   #, margins=True
df_pivot.reset_index(inplace=True)    # Reset Index

<p style="font-family:Calibri; font-size:1.75em; color:white; padding:5px 5px; text-align: left;
border-bottom: 3px solid orange; background: repeating-linear-gradient(135deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),repeating-linear-gradient(45deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),linear-gradient(90deg, rgb(77, 18, 84),rgb(52, 161, 185));"> 
Step 4  - Save Dataframe in JSON files </p>

In [31]:
#df_pivot.to_json('SaleSummary.json', orient='records')

<p style="font-family:Calibri; font-size:1.75em; color:white; padding:5px 5px; text-align: left;
border-bottom: 3px solid orange; background: repeating-linear-gradient(135deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),repeating-linear-gradient(45deg, rgba(4, 229, 71,0.08) 0px, rgba(4, 229, 71,0.08) 1px,transparent 1px, transparent 9px),linear-gradient(90deg, rgb(77, 18, 84),rgb(52, 161, 185));"> 
Step 3  - Save Dataframe in CSV files </p>

In [32]:
# Save in new csv Files
#========================
if( selRegion == "GCC"):
    df_pivot.to_csv(r'Data/4_Sales/'+cYear+'/salSummary/temp'+selRegion+'.csv', index = False)
if( selRegion == "MCS"):
    df_pivot.to_csv(r'Data/4_Sales/'+cYear+'/salSummary/temp'+selRegion+'.csv', index = False)
if( selRegion == "MCS-2"):
    df_pivot.to_csv(r'Data/4_Sales/'+cYear+'/salSummary/temp'+selRegion+'.csv', index = False)
if( selRegion == "Levant"):
    df_pivot.to_csv(r'Data/4_Sales/'+cYear+'/salSummary/temp'+selRegion+'.csv', index = False)

<p style="font-family:Calibri; font-size:1.75em; color:white; padding:5px 5px; text-align: left; height:75px;">
</p>

In [15]:
import pandas as pd
import numpy as np
  
# data
Student = {
    'Name': ['John', 'Jay', 'sachin', 'Geetha', 'Amutha', 'ganesh'],
    'gender': ['male', 'male', 'male', 'female', 'female', 'male'],
    'math score': [50, 100, 70, 80, 75, 40],
    'test preparation': ['none', 'completed', 'none', 'completed',
                         'completed', 'none'],
}
  
# creating a Dataframe object
df = pd.DataFrame(Student)
  
# Applying the condition
df.loc[df["gender"] == "male", "gender"] = 1

In [16]:
df

     Name  gender  math score test preparation
0    John       1          50             none
1     Jay       1         100        completed
2  sachin       1          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh       1          40             none